sudo: required
services:
  - docker

before_install:
  - docker build -t milivojepopovac/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run milivojepopovac/react-test npm test -- --coverage

after_success:
  - docker build -t milivojepopovac/multi-client ./client
  - docker build -t milivojepopovac/multi-nginx ./nginx
  - docker build -t milivojepopovac/multi-server ./server
  - docker build -t milivojepopovac/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push milivojepopovac/multi-client
  - docker push milivojepopovac/multi-nginx
  - docker push milivojepopovac/multi-server
  - docker push milivojepopovac/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-798660413902
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY